version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lidor123
      MYSQL_DATABASE: store
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

  node-app:
    image: lidormoryosef/taskdeeplan:001
    container_name: node-app
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: lidor123
      DB_NAME: store
      DB_PORT: 3306
    depends_on:
      - db

volumes:
  mysql-data:
