CREATE DATABASE IF NOT EXISTS store1 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE store1;
CREATE TABLE IF NOT EXISTS Product (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  catalogNumber INT NOT NULL UNIQUE CHECK (catalogNumber >= 0),
  description TEXT,
  type ENUM('Fruit', 'Vegetable', 'Field crops') NOT NULL,
  marketingDate DATE NOT NULL DEFAULT (CURRENT_DATE - INTERVAL 7 DAY),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
